library("hash")
library("xlsx")
library("xtable") # Load xtable package
library("stringr")
library("DBI")
library("RMariaDB")
library("RMySQL")
library("ggplot2")
library("factoextra")
library("NbClust")
library("dplyr")
library("lpSolve")
library("svglite")
library("shiny")

source("scripts/config.R")
source("scripts/data_definitions.R")
source("scripts/read_data.R")
source("scripts/analysis.R")
